### PR TITLE
Add navbar

### PR DESCRIPTION
**Pull request by Murph33**
Navbar only shows up for signed in users. Currently the page is only
accessible for signed in users.

### CODE REVIEW

**Comment by cbrunsdon** [comment]
@Murph33 there is too much code in here.

**Comment by Murph33** [comment]
There is so much code in here since it's pulling into master but it's branched most recently off of change_votes_to_enum.  Created the PR like this since when me and richard were going over PRs before and I had created them in that branching fashion it was adding in extra commits that shouldn't be there.  If #19 had been pulled into master I think there would only be one commit in this PR.  Whichever PR method moving forward is fine with me obviously.

**Comment by Dkendal** [comment]
If this pr is dependent on a preview pr you should probably reference it by number in the description so that people don't think you accidently pushed unrelated commits.

If the commits are not dependent you can put them in the separate PRs.

**Comment by Dkendal** [comment]
This comment extends to all other open commits.

This is really difficult to review as all open branches have shared history. You should isolate the commits into smaller grouping and push them up individually as PRs.

**Comment by Murph33** [comment]
In the future unless the commits actually depend on something in a development branch I will not branch from a development branch because that just makes sense.  #21

**Pull request closed without merging**
